---
title: 'Conceptual Issues'
author: "Bayesian Psychometric Models, Lecture 2"
date: "25 January 2019"
output: html_document
---
<!-- Replace output: line in header with these for different formatting options: -->
<!-- output: slidy_presentation --> 
<!-- output: beamer_presentation --> 
<!-- output: ioslides_presentation --> 

<!--
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
--> 

## Today's Class

1. Git (and how to access the course GitHub repo)
2. RStudio (and how to use Git within RStudio)
3. Chapters from Levy and Mislevy (2017):
    - Chapter 1: Overview of Assessment and Psychometric Modeling
    - Chapter 2
4. JAGS
5. If there is time: More from Levy and Mislevy (2017):
    - Chapter 3


## Git Clients

- If you use a Mac/Linux machine, you already have a client as part of the OS. 
- If you use Windows, you will have to download and install a client to use Git
    - A good client to use with RStudio is https://git-scm.com/download/win

 
## The Basics of Git

- Git is a version control system that helps to keep track of changes to files across the lifespan of a project
    - It is also great for using in collaboration with others
- An overview of Git is given in many places here are a few:
    - http://rogerdudler.github.io/git-guide/ (thank you, Dr. LeBeau)
    - https://git-scm.com/book/en/v2/Getting-Started-Git-Basics 
- I will use these websites to help introduce you to Git concepts
    
## Using Git with R Studio

- Git makes our life easy when used with RStudio as we can use it to keep a current copy of our course notes available
    - We will use Git to download and update our course materials in RStudio
- Do do this: 
    1. Open RStudio
    2. At the menu on the top, go to File...New Project
    3. Select "Version Control" on the "Create Project" window
    4. Select "Git" on the "Create Project from Version Control" window
    5. On the "Clone Git Repository" window input:
          - Repository URL: https://github.com/jonathantemplin/BayesianPsychometricModeling
          - Project directory name: Choose a directory name for the course materials (such as "BPM Git Repo")
              - NOTE: Any name other than bpm19ersh7375.6 will create a new .RProj file in your folder, but you can delete your file name without consequence.
              - NOTE: The file bpm1
          - Create project as a subdirectory of: Choose a location for your files to reside within on your local machine



  
    
 
## Chapter 1: Overview of Assessment and Psychometric Modeling

- Chapter provides overview of challenges of assessment
- Assessment as Evidentiary Reasoning
    - Purpose of assessment $\rightarrow$ Inferring traits of people based on their behaviors
    - Making predictions/conclusions about what is unknown from what is known 
- Another way to summarize chapter: Logic underlying assessment
<hr/>

## Toulmin Diagrams

Need graph from book


<hr/>